# -*- coding: utf-8 -*-
"""brokers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vMAaW2xAHebSq5O4th6u7v-eGUqb4b_5
"""

import streamlit as st
import pandas as pd

# -----------------------------
# DATOS COMPLETOS
# -----------------------------
data = [
["Actinver","Nacional","112,781","375,397","3,061,641",103.7,35.4,2719.2,0.7,11.8,527,"1,149,331"],
["Altor","Nacional","4,453","166","171,325,458",106.1,5.3,1635.4,0.9,21.1,43,"28,440"],
["Banorte","Nacional","215,910","20,714","79,990,173",102.3,2.8,4411.6,0.2,4.9,402,"1,656,916"],
["Barclays Capital","Filial","638","423","263,452",1431.5,4473.2,7.5,-0.5,-10.1,4,"111"],
["Base","Nacional","39,616","5,089","10,914,002",101.5,1.2,6633.6,0.4,18.5,23,"55,541"],
["BBVA Bancomer","Filial","1,790","1,291","2,462,763,994",567.3,688.3,21.4,8.0,9.2,4,"3,179,428"],
["BTG Pactual","Nacional","9,099","842","15,542,573",110.5,11.7,949.6,53.2,83.7,39,"13,087"],
["Bursamétrica","Nacional","11,016","1,265","17,890,057",102.3,-0.4,4259.3,1.8,14.5,110,"22,631"],
["Ve por Más","Nacional","23,596","11,511","11,792,092",101.3,0.8,7513.3,0.4,22.3,13,"135,739"],
["CI","Nacional","3,017","6,871","5,179,240",104.7,0.4,2134.1,0.3,21.9,92,"35,587"],
["CITI","Filial","18,581","2,474","138,237,952",146.6,1696.4,214.4,-0.2,-12.4,99,"342,001"],
["Credit Suisse","Filial","375","0","0",1691.6,8858.5,6.3,1.9,6.8,1,"6,581"],
["Deutsche Securities","Filial","30,091","0","0",110.2,619.0,980.7,0.4,0.6,38,"113"],
["Finamex","Nacional","212,558","225,675","16,407,241",101.1,47.7,9239.0,0.2,4.3,385,"3,702,704"],
["GBM","Nacional","51,755","23,821,628","46,029",103.3,3.8,3030.1,0.6,21.8,798,"1,096,489"],
["Goldman Sachs","Filial","116,819","1,928","6,190,341",115.4,95.1,650.1,1.2,15.7,53,"11,935"],
["HSBC","Filial","1,323","6","473,757,852",172.6,145.9,137.8,5.7,8.6,4,"2,843"],
["Kapital CB","Nacional","28,259","5,979","6,260,129",102.0,2.7,5117.0,0.2,11.7,137,"37,429"],
["Inversora Bursátil","Nacional","8,034","10,146","274,016,173",762.5,2075.8,15.1,9.2,8.7,124,"2,780,168"],
["Invex","Nacional","15,644","146","474,610,022",107.6,9.7,1320.8,0.8,11.4,27,"69,293"],
["JP Morgan","Filial","3,664","90","17,711,073",473.9,546.0,26.7,9.9,9.5,30,"1,594"],
["Kuspit","Nacional","695","95,967","46,803",156.9,8.8,175.7,3.3,10.8,33,"4,492"],
["Masari","Nacional","34,311","2,162","20,320,659",102.6,2.2,3904.2,0.7,8.8,332,"43,933"],
["Merrill Lynch","Filial","2,100","427","8,434,368",512.3,2486.4,24.3,21.3,27.2,35,"3,601"],
["Monex","Nacional","73,986","12,191","25,330,649",101.6,281.7,6384.3,0.5,26.2,145,"308,806"],
["Morgan Stanley","Filial","38,850","1,222","4,636,705",118.7,87.6,533.7,0.3,47.6,90,"5,666"],
["Multiva","Nacional","25,387","4,112","38,528,021",100.8,66.2,12130.0,0.2,2.2,63,"158,427"],
["Punto","Nacional","23,765","2,107","35,833,085",101.5,0.2,6454.2,0.4,22.0,50,"75,500"],
["Santander","Filial","3,558","3,141","14,355,297",276.3,1355.7,56.7,7.0,21.7,16,"45,090"],
["Scotia Inverlat","Filial","32,683","16,744","52,661,298",110.4,1038.5,964.9,2.1,15.4,311,"881,761"],
["Tactiv","Nacional","51","0","0",2199.2,1372.2,4.8,2.1,22.0,5,"372"],
["UBS","Filial","478","0","0",787.2,753.7,14.6,-18.4,-46.3,0,"3,903"],
["Valmex","Nacional","27,109","4,460","69,247,114",103.2,45.7,3143.4,0.0,-19.5,223,"308,842"],
["Value","Nacional","10,575","4,618","27,334,478",128.5,21.5,350.5,-3.3,0.7,142,"126,231"],
["Vifaru","Nacional","406","34,568","14,860",137.7,16.0,264.9,-10.2,-12.4,15,"514"]
]

columns = [
"Nombre","Tipo","Activo Total","Cuentas de Inversión","Cuenta promedio",
"Solvencia","Liquidez","Apalancamiento","ROA","ROE","Colaboradores","Cuentas de Orden"
]



### Nuevos

df = pd.DataFrame(data, columns=columns)

# -----------------------------
# INTERFAZ
# -----------------------------
st.title("Ranking Casas de Bolsa")

# Filtro tipo
tipo = st.selectbox("Tipo de capital", ["Todos", "Nacional", "Filial"])

if tipo != "Todos":
    df = df[df["Tipo"] == tipo]

# Selección indicador
indicador = st.selectbox(
    "Selecciona indicador",
    columns[2:]  # solo numéricos
)

# Orden
orden = st.radio("Orden", ["Mayor a menor", "Menor a mayor"])

ascending = True if orden == "Menor a mayor" else False

# Ordenar
df_sorted = df.sort_values(by=indicador, ascending=ascending)

# Mostrar tabla
st.subheader(f"Ranking por {indicador}")
st.dataframe(df_sorted.reset_index(drop=True))

# Top 5
st.subheader("Top 10")
st.dataframe(df_sorted.head(10).reset_index(drop=True))

# Gráfica
st.subheader("Visualización gráfica")
st.bar_chart(df_sorted.set_index("Nombre")[indicador])
