# -*- coding: utf-8 -*-
"""brokers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vMAaW2xAHebSq5O4th6u7v-eGUqb4b_5
"""

import streamlit as st
import pandas as pd

# -----------------------------
# DATOS COMPLETOS
# -----------------------------
data = [
["Actinver","Nacional",112781,375397,3061641,103.7,35.4,2719.2,0.9,21.1,527,1149331],
["Altor","Nacional",4453,166,171325458,106.1,5.3,1635.4,-0.5,-10.1,43,28440],
["Banorte","Nacional",638,423,3917060171,1431.5,4473.2,7.5,8.0,9.2,4,1656916],
["Barclays Capital","Filial",1790,1291,86321,567.3,688.3,21.4,53.2,83.7,4,111],
["Base","Nacional",9099,842,65963609,110.5,11.7,949.6,1.8,14.5,39,55541],
["BBVA Bancomer","Filial",11016,1265,2513382068,102.3,-0.4,4259.3,0.2,4.9,110,3179428],
["BTG Pactual","Nacional",215910,20714,631787,102.3,2.8,4411.6,0.4,18.5,402,13087],
["Bursamétrica","Nacional",39616,5089,4447027,101.5,1.2,6633.6,0.4,22.3,23,22631],
["Ve por Más","Nacional",23596,11511,11792092,101.3,0.8,7513.3,0.3,21.9,13,135739],
["CI","Nacional",3017,6871,5179240,104.7,0.4,2134.1,-0.2,-12.4,92,35587],
["CITI","Filial",18581,2474,138237952,146.6,1696.4,214.4,1.9,6.8,99,342001],
["Credit Suisse","Filial",375,0,0,1691.6,8858.5,6.3,0.6,0.6,1,6581],
["Deutsche Securities","Filial",30091,0,0,110.2,619.0,980.7,0.4,4.3,38,113],
["Finamex","Nacional",212558,225675,16407241,101.1,47.7,9239.0,0.2,21.8,385,3702704],
["GBM","Nacional",51755,23821628,46029,103.3,3.8,3030.1,0.6,15.7,798,1096489],
["Goldman Sachs","Filial",116819,1928,6190341,115.4,95.1,650.1,1.2,8.6,53,11935],
["HSBC","Filial",1323,6,473757852,172.6,145.9,137.8,5.7,11.7,4,2843],
["Kapital CB","Nacional",28259,5979,6260129,102.0,2.7,5117.0,0.2,8.7,137,37429],
["Inversora Bursátil","Nacional",8034,10146,274016173,762.5,2075.8,15.1,9.2,11.4,124,2780168],
["Invex","Nacional",15644,146,474610022,107.6,9.7,1320.8,0.8,9.5,27,69293],
["JP Morgan","Filial",3664,90,17711073,473.9,546.0,26.7,9.9,10.8,30,1594],
["Kuspit","Nacional",695,95967,46803,156.9,8.8,175.7,3.3,8.8,33,4492],
["Masari","Nacional",34311,2162,20320659,102.6,2.2,3904.2,0.7,27.2,332,43933],
["Merrill Lynch","Filial",2100,427,8434368,512.3,2486.4,24.3,21.3,26.2,35,3601],
["Monex","Nacional",73986,12191,25330649,101.6,281.7,6384.3,0.5,47.6,145,308806],
["Morgan Stanley","Filial",38850,1222,4636705,118.7,87.6,533.7,0.3,2.2,90,5666],
["Multiva","Nacional",25387,4112,38528021,100.8,66.2,12130.0,0.2,22.0,63,158427],
["Punto","Nacional",23765,2107,35833085,101.5,0.2,6454.2,0.4,21.7,50,75500],
["Santander","Filial",3558,3141,14355297,276.3,1355.7,56.7,7.0,15.4,16,45090],
["Scotia Inverlat","Filial",32683,16744,52661298,110.4,1038.5,964.9,2.1,22.0,311,881761],
["Tactiv","Nacional",51,0,0,2199.2,1372.2,4.8,-43.8,-46.3,5,372],
["UBS","Filial",478,0,0,787.2,753.7,14.6,-18.4,-19.5,0,3903],
["Valmex","Nacional",27109,4460,69247114,103.2,45.7,3143.4,0.0,0.7,223,308842],
["Value","Nacional",10575,4618,27334478,128.5,21.5,350.5,-3.3,-12.4,142,126231],
["Vifaru","Nacional",406,34568,14860,137.7,16.0,264.9,-10.2,-37.7,15,514]
]

columns = [
"Nombre",
"Tipo de capital",
"Activo Total",
"Cuentas de Inversión",
"Cuenta Promedio",
"Solvencia",
"Liquidez",
"Apalancamiento",
"ROA",
"ROE",
"Colaboradores",
"Cuentas de Orden"
]
### Nuevos

df = pd.DataFrame(data, columns=columns)

# -----------------------------
# INTERFAZ
# -----------------------------
st.title("Ranking Casas de Bolsa")

# Filtro tipo
tipo = st.selectbox("Tipo de capital", ["Todos", "Nacional", "Filial"])

if tipo != "Todos":
    df = df[df["Tipo"] == tipo]

# Selección indicador
indicador = st.selectbox(
    "Selecciona indicador",
    columns[2:]  # solo numéricos
)

# Orden
orden = st.radio("Orden", ["Mayor a menor", "Menor a mayor"])

ascending = True if orden == "Menor a mayor" else False

# Ordenar
df_sorted = df.sort_values(by=indicador, ascending=ascending)

# Mostrar tabla
st.subheader(f"Ranking por {indicador}")
st.dataframe(df_sorted.reset_index(drop=True))

# Top 5
st.subheader("Top 10")
st.dataframe(df_sorted.head(10).reset_index(drop=True))

# Gráfica
st.subheader("Visualización gráfica")
st.bar_chart(df_sorted.set_index("Nombre")[indicador])
