# -*- coding: utf-8 -*-
"""brokers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vMAaW2xAHebSq5O4th6u7v-eGUqb4b_5
"""

import streamlit as st
import pandas as pd

# -----------------------------
# DATOS COMPLETOS
# -----------------------------
data = [
["Actinver","Nacional",112781,1149331,98127,103.7,35.4,2719.2,0.9,21.1,527],
["Altor","Nacional",4453,28440,156579,106.1,5.3,1635.4,-0.5,-10.1,43],
["Banorte","Nacional",638,111,5722781,1431.5,4473.2,7.5,8.0,9.2,4],
["Barclays Capital","Filial",1790,3179428,563,567.3,688.3,21.4,53.2,83.7,4],
["Base","Nacional",9099,13087,695249,110.5,11.7,949.6,1.8,14.5,39],
["BBVA Bancomer","Filial",11016,22631,486788,102.3,-0.4,4259.3,0.2,4.9,110],
["BTG Pactual","Nacional",215910,1656916,130308,102.3,2.8,4411.6,0.4,18.5,402],
["Bursamétrica","Nacional",39616,55541,713273,101.5,1.2,6633.6,0.4,22.3,23],
["Ve por Más","Nacional",23596,135739,173837,101.3,0.8,7513.3,0.3,21.9,13],
["CI","Nacional",3017,35587,84791,104.7,0.4,2134.1,-0.2,-12.4,92],
["CITI","Filial",18581,342001,54330,146.6,1696.4,214.4,1.9,6.8,99],
["Credit Suisse","Filial",375,6581,56925,1691.6,8858.5,6.3,0.6,0.6,1],
["Deutsche Securities","Filial",30091,113,267357672,110.2,619.0,980.7,0.4,4.3,38],
["Finamex","Nacional",212558,3702704,57406,101.1,47.7,9239.0,0.2,21.8,385],
["GBM","Nacional",51755,1096489,47201,103.3,3.8,3030.1,0.6,15.7,798],
["Goldman Sachs","Filial",116819,11935,9787933,115.4,95.1,650.1,1.2,8.6,53],
["HSBC","Filial",1323,2843,465538,172.6,145.9,137.8,5.7,11.7,4],
["Kapital CB","Nacional",28259,37429,755005,102.0,2.7,5117.0,0.2,8.7,137],
["Inversora Bursátil","Nacional",8034,2780168,2890,762.5,2075.8,15.1,9.2,11.4,124],
["Invex","Nacional",15644,69293,225760,107.6,9.7,1320.8,0.8,9.5,27],
["JP Morgan","Filial",3664,1594,2298499,473.9,546.0,26.7,9.9,10.8,30],
["Kuspit","Nacional",695,4492,154672,156.9,8.8,175.7,3.3,8.8,33],
["Masari","Nacional",34311,43933,780973,102.6,2.2,3904.2,0.7,27.2,332],
["Merrill Lynch","Filial",2100,3601,583069,512.3,2486.4,24.3,21.3,26.2,35],
["Monex","Nacional",73986,308806,239587,101.6,281.7,6384.3,0.5,47.6,145],
["Morgan Stanley","Filial",38850,5666,6856547,118.7,87.6,533.7,0.3,2.2,90],
["Multiva","Nacional",25387,158427,160246,100.8,66.2,12130.0,0.2,22.0,63],
["Punto","Nacional",23765,75500,314767,101.5,0.2,6454.2,0.4,21.7,50],
["Santander","Filial",3558,45090,78900,276.3,1355.7,56.7,7.0,15.4,16],
["Scotia Inverlat","Filial",32683,881761,37066,110.4,1038.5,964.9,2.1,22.0,311],
["Tactiv","Nacional",51,372,137177,2199.2,1372.2,4.8,-43.8,-46.3,5],
["UBS","Filial",478,3903,122568,787.2,753.7,14.6,-18.4,-19.5,0],
["Valmex","Nacional",27109,308842,87776,103.2,45.7,3143.4,0.0,0.7,223],
["Value","Nacional",10575,126231,83779,128.5,21.5,350.5,-3.3,-12.4,142],
["Vifaru","Nacional",406,514,790279,137.7,16.0,264.9,-10.2,-37.7,15]
]

columns = [
"Nombre","Tipo","Activo Total","Cuentas","Cuenta Promedio",
"Solvencia","Liquidez","Apalancamiento","ROA","ROE","Colaboradores"
]

df = pd.DataFrame(data, columns=columns)

# -----------------------------
# INTERFAZ
# -----------------------------
st.title("Ranking Casas de Bolsa")

# Filtro tipo
tipo = st.selectbox("Tipo de capital", ["Todos", "Nacional", "Filial"])

if tipo != "Todos":
    df = df[df["Tipo"] == tipo]

# Selección indicador
indicador = st.selectbox(
    "Selecciona indicador",
    columns[2:]  # solo numéricos
)

# Orden
orden = st.radio("Orden", ["Mayor a menor", "Menor a mayor"])

ascending = True if orden == "Menor a mayor" else False

# Ordenar
df_sorted = df.sort_values(by=indicador, ascending=ascending)

# Mostrar tabla
st.subheader(f"Ranking por {indicador}")
st.dataframe(df_sorted.reset_index(drop=True))

# Top 5
st.subheader("Top 10")
st.dataframe(df_sorted.head(10).reset_index(drop=True))

# Gráfica
st.subheader("Visualización gráfica")
st.bar_chart(df_sorted.set_index("Nombre")[indicador])